assets:
  settings.xml: yegor256/home#assets/sttc/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
  s3cfg: yegor256/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install:
- sudo gem install pdd
deploy:
  script: |
    mvn clean install -Prultor --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=sttc-stateful.xml
    s3cmd --no-progress put sttc-stateful.xml --config=../s3cfg s3://pdd.teamed.io/sttc-stateful.xml
  commanders:
  - yegor256
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Psttc-web --errors --batch-mode
    git remote add heroku git@heroku.com:stateful.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add settings.xml
    git commit -m 'settings.xml'
    git fetch --unshallow
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.stateful.co
    mvn clean site-deploy -Psite --batch-mode --settings ../settings.xml
merge:
  script: |-
    mvn help:system clean install -Pqulice --settings ../settings.xml
    mvn clean site -Psite --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - yegor256
architect:
- karato
- yegor256