# SPDX-FileCopyrightText: Copyright (c) 2014-2026, Stateful.co
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
readers:
  - "urn:github:526301"
assets:
  settings.xml: yegor256/home#assets/sttc/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
release:
  sensitive:
    - settings.xml
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/webapp/META-INF/MANIFEST.MF
    git add src/main/resources/webapp/META-INF/MANIFEST.MF
    git commit -m 'build number set'
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Psttc-web --errors --batch-mode
    git remote add dokku dokku@www.stateful.co:stateful
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add settings.xml
    git fetch
    git commit -m 'settings.xml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm settings.xml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.stateful.co
    # mvn clean site-deploy -Psite --batch-mode --settings ../settings.xml
merge:
  script: |-
    mvn help:system clean install -Pqulice --settings ../settings.xml
    mvn clean site -Psite --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
