assets:
  settings.xml: "yegor256/home#assets/sttc/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

install:
  - "sudo gem install pdd"

deploy:
  script:
    - "mvn clean install -Prultor --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=sttc-stateful.xml"
    - "s3cmd --no-progress put sttc-stateful.xml --config=../s3cfg s3://pdd.teamed.io/sttc-stateful.xml"

release:
  script:
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Psttc --settings ../settings.xml"
    - "mvn clean site-deploy -Psite --settings ../settings.xml"

merge:
  script:
    - "mvn help:system clean install -Pqulice --settings ../settings.xml"
    - "mvn clean site -Psite --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=/dev/null"
