language: java
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - unset GEM_PATH
script:
  - mvn clean install -Pqulice --quiet --batch-mode --errors

